import type * as schema from '../db/schema'

export const courses: (typeof schema.courses.$inferSelect)[] = [
  {
    id: 1,
    title: '英语',
    imageSrc: '/US.svg',
  },
  {
    id: 2,
    title: '西班牙语',
    imageSrc: '/ES.svg',
  },
  {
    id: 3,
    title: '法语',
    imageSrc: '/FR.svg',
  },
  {
    id: 4,
    title: '意大利语',
    imageSrc: '/IT.svg',
  },
  {
    id: 5,
    title: '日语',
    imageSrc: '/JP.svg',
  },
]

export const units: (typeof schema.units.$inferSelect)[] = [
  {
    id: 1,
    courseId: 1,
    title: '第1阶段，第1部分',
    description: '连词成句',
    order: 1,
  },
  {
    id: 2,
    courseId: 1,
    title: '第一阶段，第2部分',
    description: '介绍简单的物品和颜色',
    order: 2,
  },
]

export const lessons: (typeof schema.lessons.$inferSelect)[] = [
  {
    id: 1,
    unitId: 1,
    order: 1,
    title: '第一单元',
  },
  {
    id: 2,
    unitId: 1,
    order: 2,
    title: '第二单元',
  },
  {
    id: 3,
    unitId: 1,
    order: 3,
    title: '第3单元',
  },
  {
    id: 4,
    unitId: 1,
    order: 4,
    title: '第1部分总复习',
  },
  {
    id: 5,
    unitId: 2,
    order: 1,
    title: '第1单元',
  },
  {
    id: 6,
    unitId: 2,
    order: 2,
    title: '第2单元',
  },
  {
    id: 7,
    unitId: 2,
    order: 3,
    title: '第3单元',
  },
  {
    id: 8,
    unitId: 2,
    order: 4,
    title: '第2部分总复习',
  },
]

export const challenges: (typeof schema.challenges.$inferSelect)[] = [
  {
    id: 1,
    lessonId: 1,
    type: 'SELECT',
    order: 1,
    question: '哪个是“狗”呢？',
  },
  {
    id: 2,
    lessonId: 1,
    type: 'ASSIST',
    order: 2,
    question: '哪个是“老师”呢？',
  },
  {
    id: 3,
    lessonId: 1,
    type: 'SELECT',
    order: 3,
    question: '哪个是“猫”呢？',
  },
  {
    id: 4,
    lessonId: 2,
    type: 'SELECT',
    order: 1,
    question: '哪个是“母亲”呢？',
  },
  {
    id: 5,
    lessonId: 2,
    type: 'ASSIST',
    order: 2,
    question: '哪个是“学生”呢？',
  },
  {
    id: 6,
    lessonId: 2,
    type: 'SELECT',
    order: 3,
    question: '哪个是“父亲”呢？',
  },
]

export const challengesOptions: (typeof schema.challengeOptions.$inferSelect)[] = [
  {
    id: 1,
    challengeId: 1,
    text: 'dog',
    correct: true,
    imageSrc: '/us_dog.svg',
    audioSrc: '/us_dog.mp3',
  },
  {
    id: 2,
    challengeId: 1,
    text: 'father',
    correct: false,
    imageSrc: '/us_father.svg',
    audioSrc: '/us_father.mp3',
  },
  {
    id: 3,
    challengeId: 1,
    text: 'cat',
    correct: false,
    imageSrc: '/us_cat.svg',
    audioSrc: '/us_cat.mp3',
  },
  {
    id: 4,
    challengeId: 2,
    text: 'student',
    correct: false,
    imageSrc: '',
    audioSrc: '/us_student.mp3',
  },
  {
    id: 5,
    challengeId: 2,
    text: 'teacher',
    correct: true,
    imageSrc: '',
    audioSrc: '/us_teacher.mp3',
  },
  {
    id: 6,
    challengeId: 2,
    text: 'mother',
    correct: true,
    imageSrc: '',
    audioSrc: '/us_mother.mp3',
  },
  {
    id: 7,
    challengeId: 3,
    text: 'cat',
    correct: true,
    imageSrc: '/us_cat.svg',
    audioSrc: '/us_cat.mp3',
  },
  {
    id: 8,
    challengeId: 3,
    text: 'student',
    correct: false,
    imageSrc: '/us_student.svg',
    audioSrc: '/us_student.mp3',
  },
  {
    id: 9,
    challengeId: 3,
    text: 'mother',
    correct: false,
    imageSrc: '/us_mother.svg',
    audioSrc: '/us_mother.mp3',
  },
  {
    id: 10,
    challengeId: 4,
    text: 'mother',
    correct: true,
    imageSrc: '/us_mother.svg',
    audioSrc: '/us_mother.mp3',
  },
  {
    id: 11,
    challengeId: 4,
    text: 'father',
    correct: false,
    imageSrc: '/us_father.svg',
    audioSrc: '/us_father.mp3',
  },
  {
    id: 12,
    challengeId: 4,
    text: 'cat',
    correct: false,
    imageSrc: '/us_cat.svg',
    audioSrc: '/us_cat.mp3',
  },
  {
    id: 13,
    challengeId: 5,
    text: 'student',
    correct: true,
    imageSrc: '',
    audioSrc: '/us_student.mp3',
  },
  {
    id: 14,
    challengeId: 5,
    text: 'teacher',
    correct: false,
    imageSrc: '',
    audioSrc: '/us_teacher.mp3',
  },
  {
    id: 15,
    challengeId: 5,
    text: 'mother',
    correct: true,
    imageSrc: '',
    audioSrc: '/us_mother.mp3',
  },
  {
    id: 16,
    challengeId: 6,
    text: 'cat',
    correct: false,
    imageSrc: '/us_cat.svg',
    audioSrc: '/us_cat.mp3',
  },
  {
    id: 17,
    challengeId: 6,
    text: 'student',
    correct: false,
    imageSrc: '/us_student.svg',
    audioSrc: '/us_student.mp3',
  },
  {
    id: 18,
    challengeId: 6,
    text: 'father',
    correct: true,
    imageSrc: '/us_father.svg',
    audioSrc: '/us_father.mp3',
  },
]
